title: 'YOLOnerds'
url: "https://yolonerds.com"
twitter_username: yolonerds
github_username:  lzychowski

# Conversion
markdown: kramdown

# Files
exclude: ['node_modules']

# Highlighter: rouge
kramdown:
   input: GFM
   syntax_highlighter: rouge

# Serving
host: https://yolonerds.com

# Paging
paginate: 10
paginate_path: "/page:num/"

# Gems
gems: [jekyll-paginate]